name: wallet_dart
description: Candide helper/essential shared functions.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  web3dart: ^2.5.1
  eth_sig_util: ^0.0.9
  http: ^0.13.5
  steel_crypt: ^3.0.0+1
  pointycastle: ^3.6.2
  flutter:
    sdk: flutter

dev_dependencies:
  web3dart_builders: ^0.0.2
  build_runner: ^2.0.3
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
